POST http://localhost:3010/add-master
Content-Type: application/json 

{
 "username":"Arun Kumar",
 "email":"arunnandu333@gmail.com",
 "password":"Arun@7328",
 "id":"2"
}

### 
POST http://localhost:3010/add-student
Content-Type: application/json 

{
 "username":"Arun Kumar",
 "email":"arunnandu333@gmail.com",
 "password":"Arun@7328",
 "id":"2"
}


### 
POST http://localhost:3010/login-master
Content-Type: application/json 

{
 "username":"Arun Kumar",
 "password":"Arun@7328"
}

### 
POST http://localhost:3010/login-student
Content-Type: application/json 

{
 "username":"Keerthi",
 "password":"Arun@7328"
}

###
POST http://localhost:3010/master-questions/send
Content-Type: application/json 

{
 "id":"2",
 "question":"3*7",
 "masterId":"2",
 "masterName":"Arun Kumar"
}

### 
POST http://localhost:3010/student-answer/send
Content-Type: application/json 

{
 "id":"1",
 "question":"3*7",
 "studentId":"1",
 "studentName":"Keerthi",
 "answer":"21"
}

### 
GET http://localhost:3010/all/questions 

### 
GET http://localhost:3010/all/answers

### 
GET http://localhost:3010/get/master/question/1 

### 
GET http://localhost:3010/get/master/name/1 

### 
GET http://localhost:3010/get/student/name/1 

